### ISSUE TITLE
Idea: Edit content before return 

### ISSUE THREAD

**Issue by sh-sh-dev** [brozeph/simple-socks#23]
Is it possible to edit response before returning to the client?

For example show a "Your subscription has been expired" page
or remove ads from page and then return result (like many other VPNs)

**Comment by dagli** [comment]
> For example return "The subscription has expired"

You can do this with authentication mechanism. In addition to user&pass check, add the subscription expiration check.

**Comment by brozeph** [comment]
Closing as answered
