### ISSUE TITLE
Upstream SOCKS5 Server

### ISSUE THREAD

**Issue by regbo** [brozeph/simple-socks#25]
I am interested in using your server in the folowing configuration. We currently have SOCKS5 proxies that do not support authentication. We'd like to have this setup:

CLIENT ---> SIMPLE-SOCKS ---> CURRENT_SOCKS5 _PROXY ---> WEB/WHATEVER

Is this possible? Furthermore, is it possible to somehow configure it like so?

  server1 = socks5.createServer().listen(1080).upstream("socks5://host:1080");
  server2= socks5.createServer().listen(1081).upstream("socks5://host:1081");

**Comment by brozeph** [comment]
Hi @regbo  - based on this, it sounds like you are want to add an authentication layer for a subset / portion of the traffic that is currently passed through CURRENT_SOCKS5_PROXY. If you want all traffic to be password protected, do you have the option to replace the current SOCKS5 proxies?

**Comment by brozeph** [comment]
Closing issue due to time - can re-open as needed
