### ISSUE TITLE
How to White-list Url's? Proxy only allowed urls.

### ISSUE THREAD

**Issue by Technologeek** [brozeph/simple-socks#29]
Thanks for the beautiful piece of code. I'm running a proxy server locally (that is pointing my network settings to the proxy server). This proxies logs all of the network traffic including my slack, Spotify and so on. However, I need only a list of given url's to be proxied. Like if an user enters a url which is not allowed by my proxy server then his request shouldn't go through. How can I achieve it using this proxy?

**Comment by brozeph** [comment]
Hey @Technologeek - check out this example here: <https://github.com/brozeph/simple-socks/blob/master/examples/createServerConnectionFilter.js>

The example is kinda light, but gives the general idea. Effectively, the `createServer` method accepts an object where a `connectionFilter` method can be provided. This method has the following signature: `function (port, address, socket, callback)` and the `address` parameter, in particular, can be used to understand the destination of the request and use that for filtering. If you want to a tad more sophisticated, you may want to look at using the `dns` module from the Node core to do reverse IP lookups if the `address` is not a domain name (<https://nodejs.org/dist/latest-v10.x/docs/api/dns.html#dns_dns_reverse_ip_callback>).

**Comment by Technologeek** [comment]
@brozeph Thanks a million for the quick reply! I'll certainly look into that module and update this post for the future reference. Also, is there a way to get the response data from the proxy itself?  Right now I'm using the requests library to get the response data which basically involves two calls

```
socks5 = require('simple-socks'),
server = socks5.createServer().listen(3000);
const request = require('request');

// When a reqest arrives for a remote destination
server.on('proxyConnect', function (info, destination) {
  console.log('connected to remote server at %s:%d', info.host, info.port);
  console.log(destination)
  let abc = request("http://"+ info.host, function (error, response, body) {
      //console.log(abc)
  //console.log('error:', error); // Print the error if one occurred
  //console.log('statusCode:', response && response.statusCode); // Print the response status code if a response was received
  //console.log('body:', body); // Print the HTML for the Google homepage.
});
```

Is there  direct way to print the response data from the proxy itself?

**Comment by brozeph** [comment]
@Technologeek  - sorry for the late response here, but yes, you can grab the response data directly using the socket that is exposed via the `proxyConnect` event ([https://github.com/brozeph/simple-socks/#proxyconnect]). Alternatively, you can use the `proxyData` event to capture and work with the data directly ([https://github.com/brozeph/simple-socks/#proxydata])!

```javascript
socks5 = require('simple-socks'),
server = socks5.createServer().listen(3000);

// When a reqest arrives for a remote destination
server.on('proxyData', function (data) {
  console.log('data received from remote destination: %d', data.length);
});
```
