### ISSUE TITLE
request proxyDisconnect event

### ISSUE THREAD

**Issue by sh-sh-dev** [brozeph/simple-socks#41]
I want to limit connected devices count per user (for example sell a 2 devices subscription)
The database and codes are ready. But there is a problem. Here is the scenario:

1. Each time the `proxyConnect` fired, We count a connection for the user to limit the number of connections (1 of 2 devices is remaining).
2. And each time the `proxyDisconnect` event fired, We know that the user connection has been closed, So we revoke the step 1 connection (2 of 2 devices is remaining).

So we need a `proxyDisconnect` event to run this scenario. Thanks for your time.

**Comment by brozeph** [comment]
Added `proxyDisconnect` in `v2.1.0` - closing now with link to updated documentation: <https://github.com/brozeph/simple-socks#proxydisconnect>
