### ISSUE TITLE
Https doesn't work with the windows proxy settings

### ISSUE THREAD

**Issue by ortexx** [brozeph/simple-socks#42]
I am testing the library. It works well with firefox proxy setting ans some other browsers as well. But it doesn't open **https** pages in chrome and similar ones that works with windows internet options. I got **ERR_PROXY_CONNECTION_FAILED** on the client side and 

```
socket closed with code 1
{ ver: 4, nmethods: 1, methods: <Buffer 08> } 
```

on the proxy side.
What could be the reason?

**Comment by brozeph** [comment]
@ortexx, thank you for submitting this issue.

After doing some further research, I started to zero in on the version (in your case, 4). I found some additional info I found helpful. Specifically, see the following issue from a different proxy repo: <https://github.com/alexkirsz/dispatch-proxy/issues/63#issuecomment-321072224>

Ultimately, I was able to get this to work by ensuring the system was using the server as a proxy server.
