### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by elbandi** [brozeph/simple-socks#5]
I wanted to use hexchat with this. i set (just for test) invalid password in hexchat. After i try to connect. i got this in proxy:

```
------------------------------------------------------------
new client connection
user elbandi_ failed to authenticate...
[Error: invalid credentials]
socket closed with code 255
{ ver: 1,
  ulen: 8,
  uname: <Buffer 65 6c 62 61 6e 64 69 5f>,
  plen: 5,
  passwd: <Buffer 6b 75 6b 61 63>,
  requestBuffer: <Buffer 01 ff 65 6c 62 61 6e 64 69 5f 05 6b 75 6b 61 63> }


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
```

**Comment by avargas** [comment]
I'm not entirely sure how to trap the authentication errors yet, but you could use `process.on('uncaughtException',  function (err) {}`

It's not the best practice but it makes the script function work.

**Comment by brozeph** [comment]
@avargas does the example at https://github.com/brozeph/simple-socks#authenticateerror help?

If not, would it be possible to share a few more details on the callback function where the credentials are validated?

**Comment by avargas** [comment]
No, I am using a slightly modified version of this example https://github.com/brozeph/simple-socks/blob/master/examples/createServerWithAuthentication.js  and it still fails. I meant to look over your code and try to fix it, but I haven't had time.

**Comment by elbandi** [comment]
i think this is happening: after the end function sent back the error message to client, the client got this error message, and close his connection. this server still try to read something on a closed connection, this is bad. so somewhere we need to catch this, and destroy our connection handle too

**Comment by brozeph** [comment]
I published an update where the authentication callback occurs within an isolated domain - this should resolve the error. With your existing code, utilizing this new version, can you let me know if the un-handled exception you are seeing is still occurring?

**Comment by brozeph** [comment]
Added code to listen to the `error` event that is surfaced by the underlying socket that is created when establishing each new connection. These events are now passed through to the `proxyError` event on the proxy server itself.
